extends Node

const CLIENT_VIEW_ABOUT = "CLIENT_VIEW_ABOUT"
const CLIENT_VIEW_ACHIEVEMENTS = "CLIENT_VIEW_ACHIEVEMENTS"
const CLIENT_VIEW_MAIN_MENU = "CLIENT_VIEW_MAIN_MENU"
const CLIENT_VIEW_NONE = "CLIENT_VIEW_NONE"
