extends Node

const CLIENT_PERSISTENT_STORE_PATH = "user://persistent-store.tres"
const CLIENT_VIEW_ABOUT = "CLIENT_VIEW_ABOUT"
const CLIENT_VIEW_ACHIEVEMENTS = "CLIENT_VIEW_ACHIEVEMENTS"
const CLIENT_VIEW_CREDITS = "CLIENT_VIEW_CREDITS"
const CLIENT_VIEW_GAME_OVER = "CLIENT_VIEW_GAME_OVER"
const CLIENT_VIEW_MAIN_MENU = "CLIENT_VIEW_MAIN_MENU"
const CLIENT_VIEW_NONE = "CLIENT_VIEW_NONE"
const CLIENT_VIEW_SPLASH = "CLIENT_VIEW_SPLASH"
