extends Node

const GAME_SET_START_TIME = "GAME_SET_START_TIME"

const PLAYER_DAMAGE = "PLAYER_DAMAGE"
const PLAYER_SET_FOOD = "PLAYER_SET_FOOD"
const PLAYER_SET_GOLD = "PLAYER_SET_GOLD"
const PLAYER_SET_HEALTH = "PLAYER_SET_HEALTH"
const PLAYER_SET_STATE = "PLAYER_SET_STATE"
const PLAYER_SET_TILE = "PLAYER_SET_TILE"

const TILES_SET_CHILD = "TILES_SET_CHILD"
